#!/usr/bin/env python3
"""Validate a static workflow DAG and emit a Hermes execution driver.

YAML node keys:
  task: required string
  output: required relative file path
  depends_on: optional list of node names
  checks: optional shell commands; supports {output}; exit 0 = valid handoff

Commands:
  plan workflow.yaml   # validate schema/DAG and print waves
  run workflow.yaml    # emit Python driver for execute_code

This runner handles static edges and fan-out/fan-in. Conditional reject-routing
is orchestrated by Hermes after reading a router artifact; it is not executed by
this static DAG runner.
"""
import json
import os
import pathlib
import sys
import yaml

STATE_DIR = os.path.expanduser("~/.hermes/state/graphs")


def safe_relative(value, field):
    p = pathlib.PurePosixPath(value)
    if p.is_absolute() or ".." in p.parts or str(p) in ("", "."):
        raise SystemExit(f"unsafe {field}: {value!r}")
    return str(p)


def load(path):
    with open(path, encoding="utf-8") as f:
        doc = yaml.safe_load(f) or {}
    nodes = doc.get("nodes")
    if not isinstance(nodes, dict) or not nodes:
        raise SystemExit("workflow needs a non-empty 'nodes' mapping")
    name = doc.get("workflow", os.path.basename(path).split(".")[0])
    safe_relative(name, "workflow name")
    outputs = set()
    for node, cfg in nodes.items():
        if not isinstance(cfg, dict):
            raise SystemExit(f"node {node}: config must be a mapping")
        if not isinstance(cfg.get("task"), str) or not cfg["task"].strip():
            raise SystemExit(f"node {node}: task must be a non-empty string")
        if "output" not in cfg:
            raise SystemExit(f"node {node}: output is required (typed artifact contract)")
        cfg["output"] = safe_relative(str(cfg["output"]), f"node {node} output")
        if cfg["output"] in outputs:
            raise SystemExit(f"duplicate output path: {cfg['output']}")
        outputs.add(cfg["output"])
        deps = cfg.get("depends_on", [])
        if not isinstance(deps, list) or not all(isinstance(d, str) for d in deps):
            raise SystemExit(f"node {node}: depends_on must be a list of node names")
        unknown = [d for d in deps if d not in nodes]
        if unknown:
            raise SystemExit(f"node {node}: unknown dependencies: {', '.join(unknown)}")
        if node in deps:
            raise SystemExit(f"node {node}: self-dependency is invalid")
        checks = cfg.get("checks", [])
        if not isinstance(checks, list) or not all(isinstance(c, str) for c in checks):
            raise SystemExit(f"node {node}: checks must be a list of shell commands")
    return name, nodes


def waves(nodes):
    done, order, remaining = set(), [], dict(nodes)
    while remaining:
        ready = sorted(n for n, cfg in remaining.items() if set(cfg.get("depends_on", [])) <= done)
        if not ready:
            raise SystemExit("dependency cycle among: " + ", ".join(sorted(remaining)))
        order.append(ready)
        for node in ready:
            done.add(node)
            del remaining[node]
    return order


def plan(path):
    name, nodes = load(path)
    order = waves(nodes)
    print(f"workflow: {name} ({len(nodes)} nodes, {len(order)} waves)")
    for idx, wave in enumerate(order, 1):
        for node in wave:
            cfg = nodes[node]
            deps = ",".join(cfg.get("depends_on", [])) or "-"
            checks = len(cfg.get("checks", []))
            print(f"  wave {idx}: {node:20s} deps={deps:30s} checks={checks} -> {cfg['output']}")
    return order


def emit_runner(path):
    name, nodes = load(path)
    order = waves(nodes)
    outdir = os.path.join(STATE_DIR, name)
    lines = [
        "# Generated by graph-runner.py. Execute with execute_code.",
        "from hermes_tools import delegation, terminal, write_file",
        "import json, os, time",
        f"OUTDIR = {outdir!r}",
        "os.makedirs(OUTDIR, exist_ok=True)",
        "def result_text(value):",
        "    if isinstance(value, dict):",
        "        return str(value.get('result') or value.get('summary') or value.get('output') or '')",
        "    return str(value)",
        "def validate(path, checks):",
        "    if not os.path.isfile(path) or os.path.getsize(path) == 0:",
        "        raise RuntimeError(f'empty/missing artifact: {path}')",
        "    for raw in checks:",
        "        command = raw.replace('{output}', path)",
        "        r = terminal(command)",
        "        if r.get('exit_code', 1) != 0:",
        "            raise RuntimeError(f'handoff check failed: {command}: {r}')",
    ]
    for idx, wave in enumerate(order, 1):
        tasks = []
        for node in wave:
            cfg = nodes[node]
            deps = cfg.get("depends_on", [])
            dep_files = [os.path.join(outdir, nodes[d]["output"]) for d in deps]
            outfile = os.path.join(outdir, cfg["output"])
            context = (
                f"You are node '{node}' in workflow '{name}'. Do ONLY this bounded job. "
                "Return the finished artifact as your final message; no process commentary. "
                f"You may write only this declared artifact: {outfile}. "
                "Shared input artifacts are read-only.\n\n"
                f"TASK: {cfg['task']}\n"
            )
            if dep_files:
                context += "READ-ONLY INPUT ARTIFACTS (account for every one): " + ", ".join(dep_files) + "\n"
            tasks.append({"goal": f"Node '{node}' of workflow '{name}'", "context": context})
        lines.append(f"# wave {idx}: {', '.join(wave)}")
        lines.append(f"res_{idx} = delegation(tasks={json.dumps(tasks)})")
        lines.append(f"if len(res_{idx}) != {len(wave)}: raise RuntimeError('wave {idx} result count mismatch')")
        for result_idx, node in enumerate(wave):
            cfg = nodes[node]
            outfile = os.path.join(outdir, cfg["output"])
            lines.append(f"text = result_text(res_{idx}[{result_idx}])")
            lines.append(f"if not text.strip(): raise RuntimeError('node {node} returned empty output')")
            lines.append(f"write_file({outfile!r}, text)")
            lines.append(f"validate({outfile!r}, {json.dumps(cfg.get('checks', []))})")
        lines.append(f"print('wave {idx} verified:', {wave!r})")
    krlog = os.path.expanduser("~/.hermes/state/keep-rate.jsonl")
    lines += [
        f"with open({krlog!r}, 'a') as f:",
        f"    f.write(json.dumps({{'ts': int(time.time()), 'loop': {name!r}, 'kept': True, 'outcome': 'graph:done'}}) + '\\n')",
        f"print('GRAPH COMPLETE -> {outdir}')",
    ]
    print("\n".join(lines))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: graph-runner.py plan|run <workflow.yaml>")
    command, workflow = sys.argv[1:]
    if command == "plan": plan(workflow)
    elif command == "run": emit_runner(workflow)
    else: raise SystemExit("usage: graph-runner.py plan|run <workflow.yaml>")
